const products = [
  {
    cod: "1",
    name: "Queijo Mussarela",
    price: 51.0,
    unit: "kg",
    badge: "Davac",
    characteristic: "",
    category: "Frios",
    description: "",
    image: "",
  },
  {
    cod: "2",
    name: "Presunto",
    price: 26.0,
    unit: "kg",
    badge: "Seaara",
    characteristic: "",
    category: "Frios",
    description: "",
    image: "",
  },
  {
    cod: "3",
    name: "H2o Limoneto",
    price: 6.99,
    unit: "un",
    size: "1.5L",
    badge: "",
    characteristic: "",
    category: "Bebidas",
    description: "",
    image: "",
  },
  {
    cod: "4",
    name: "Energético Fusion",
    price: 6.99,
    unit: "un",
    size: "1L",
    badge: "",
    characteristic: "",
    category: "Bebidas",
    description: "",
    image: "",
  },
  {
    cod: "5",
    name: "Nescaú",
    price: 13.0,
    unit: "un",
    size: "400g",
    badge: "30% menos açucar",
    characteristic: "",
    category: "Bebidas",
    description: "",
    image: "",
  },
  {
    cod: "6",
    name: "Água Sanitária",
    price: 2,
    unit: "un",
    size: "1L",
    badge: "Dragão",
    characteristic: "",
    category: "Limpeza",
    description: "",
    image: "",
  },
  {
    cod: "7",
    name: "Cream Cracker",
    price: 6.0,
    unit: "un",
    size: "400g",
    badge: "",
    characteristic: "",
    category: "Massas",
    description: "",
    image: "",
  },
  {
    cod: "8",
    name: "Bolacha Maria",
    price: 6.0,
    unit: "un",
    size: "400g",
    badge: "Pillar",
    characteristic: "",
    category: "Massas",
    description: "",
    image: "",
  },
  {
    cod: "9",
    name: "Sardinha",
    price: 5.5,
    unit: "un",
    size: "125g",
    badge: "Coqueiro",
    characteristic: "Tomate",
    category: "Proteinas",
    description: "",
    image: "",
  },
  {
    cod: "10",
    name: "Atum",
    price: 8.5,
    unit: "un",
    size: "125g",
    badge: "",
    characteristic: "",
    category: "Proteinas",
    description: "",
    image: "",
  },
  {
    cod: "11",
    name: "Tomate",
    price: 7,
    unit: "kg",
    size: "",
    badge: "",
    characteristic: "",
    category: "Hortifruti",
    description: "",
    image: "",
  },
  {
    cod: "12",
    name: "Cebola",
    price: 5.0,
    unit: "kg",
    size: "",
    badge: "",
    characteristic: "",
    category: "Hortifruti",
    description: "",
    image: "",
  },
  {
    cod: "13",
    name: "Manga",
    price: 10.0,
    unit: "kg",
    size: "",
    badge: "",
    characteristic: "",
    category: "Hortifruti",
    description: "",
    image: "",
  },
  {
    cod: "14",
    name: "Maçã",
    price: 11.0,
    unit: "kg",
    size: "",
    badge: "fuji",
    characteristic: "",
    category: "Hortifruti",
    description: "",
    image: "",
  },
  {
    cod: "15",
    name: "Pão de Forma Integral",
    price: 15.0,
    unit: "un",
    size: "500g",
    badge: "Plus Vita",
    characteristic: "",
    category: "Massas",
    description: "",
    image: "",
  },
  {
    cod: "16",
    name: "Ovos",
    price: 10.0,
    unit: "dz",
    size: "",
    badge: "",
    characteristic: "",
    category: "Proteinas",
    description: "",
    image: "",
  },
  {
    cod: "17",
    name: "Requeijão Light",
    price: 7.0,
    unit: "un",
    size: "200g",
    badge: "O mais barato",
    characteristic: "",
    category: "Frios",
    description: "",
    image: "",
  },
  {
    cod: "18",
    name: "H2o Limão",
    price: 6.5,
    unit: "un",
    size: "1.5L",
    badge: "",
    characteristic: "",
    category: "Bebidas",
    description: "",
    image: "",
  },
  {
    cod: "19",
    name: "Leão Ice Tea",
    price: 6.3,
    unit: "un",
    size: "1L",
    badge: "",
    characteristic: "",
    category: "Bebidas",
    description: "",
    image: "",
  },
  {
    cod: "20",
    name: "Sabão em Pó",
    price: 14.0,
    unit: "un",
    size: "800g",
    badge: "Omo",
    characteristic: "",
    category: "Limpeza",
    description: "",
    image: "",
  },
  {
    cod: "21",
    name: "Sabão em Pó",
    price: 5.0,
    unit: "un",
    size: "250g",
    badge: "Genérico",
    characteristic: "",
    category: "Limpeza",
    description: "",
    image: "",
  },
  {
    cod: "22",
    name: "Sabonete",
    price: 3.5,
    unit: "un",
    size: "90g",
    badge: "Protex",
    characteristic: "",
    category: "Limpeza",
    description: "",
    image: "",
  },
  {
    cod: "23",
    name: "Milho Verde",
    price: 5,
    unit: "un",
    size: "200g",
    badge: "Quero",
    characteristic: "",
    category: "Conservas",
    description: "",
    image: "",
  },
  {
    cod: "24",
    name: "Trident",
    price: 2.3,
    unit: "un",
    size: "14g",
    badge: "",
    characteristic: "",
    category: "Doces",
    description: "",
    image: "",
  },
  {
    cod: "26",
    name: "Pote de Plástico",
    price: 5.0,
    unit: "un",
    size: "1un",
    badge: "",
    characteristic: "",
    category: "Utensílios",
    description: "",
    image: "",
  },

  {
    cod: "27",
    name: "Papel Higiênico",
    price: 8.0,
    unit: "un",
    size: "4un",
    badge: "",
    characteristic: "",
    category: "Limpeza",
    description: "",
    image: "",
  },
  {
    cod: "28",
    name: "Detergente",
    price: 2.5,
    unit: "un",
    size: "500ml",
    badge: "Limpol",
    characteristic: "Neutro",
    category: "Limpeza",
    description: "",
    image: "",
  },
  {
    cod: "29",
    name: "Alcool 70%",
    price: 10.0,
    unit: "un",
    size: "500ml",
    badge: "",
    characteristic: "",
    category: "Limpeza",
    description: "",
    image: "",
  },
  {
    cod: "30",
    name: "Desinfetante",
    price: 5.5,
    unit: "un",
    size: "500ml",
    badge: "Dragão",
    characteristic: "",
    category: "Limpeza",
    description: "",
    image: "",
  },
  {
    cod: "32",
    name: "Barbeador",
    price: 10.0,
    unit: "un",
    size: "",
    badge: "",
    characteristic: "",
    category: "Higiene",
    description: "",
    image: "",
  },
  {
    cod: "33",
    name: "Creme Dental",
    price: 15.0,
    unit: "un",
    size: "90g",
    badge: "Colgate",
    characteristic: "",
    category: "Higiene",
    description: "",
    image: "",
  },
  {
    cod: "34",
    name: "Amaciante",
    price: 10.0,
    unit: "un",
    size: "2L",
    badge: "",
    characteristic: "",
    category: "Limpeza",
    description: "",
    image: "",
  },
  {
    cod: "35",
    name: "Pimentão",
    price: 5.0,
    unit: "kg",
    size: "",
    badge: "",
    characteristic: "",
    category: "Hortifruti",
    description: "",
    image: "",
  },
  {
    cod: "36",
    name: "Biscoito Nestfit",
    price: 4.5,
    unit: "un",
    size: "140g",
    badge: "",
    characteristic: "",
    category: "Biscoitos",
    description: "",
    image: "",
  },
  {
    cod: "37",
    name: "Batata Doce",
    price: 4.0,
    unit: "kg",
    size: "",
    badge: "",
    characteristic: "",
    category: "Hortifruti",
    description: "",
    image: "",
  },
  {
    cod: "38",
    name: "Azeite",
    price: 24.0,
    unit: "un",
    size: "500ml",
    badge: "Andorinha",
    characteristic: "",
    category: "Temperos",
    description: "",
    image: "",
  },
  {
    cod: "39",
    name: "Polpa Goiaba",
    price: 1.0,
    unit: "un",
    size: "100g",
    badge: "",
    characteristic: "",
    category: "Hortifruti",
    description: "",
    image: "",
  },
  {
    cod: "40",
    name: "Polpa Graviola",
    price: 1.0,
    unit: "un",
    size: "100g",
    badge: "",
    characteristic: "",
    category: "Hortifruti",
    description: "",
    image: "",
  },
  {
    cod: "41",
    name: "Polpa Caju",
    price: 1.0,
    unit: "un",
    size: "100g",
    badge: "",
    characteristic: "",
    category: "Hortifruti",
    description: "",
    image: "",
  },
  {
    cod: "42",
    name: "Polpa Maraçujá",
    price: 1.0,
    unit: "un",
    size: "100g",
    badge: "",
    characteristic: "",
    category: "Hortifruti",
    description: "",
    image: "",
  },
  {
    cod: "43",
    name: "Biscoito Goiabinha",
    price: 4.5,
    unit: "un",
    size: "140g",
    badge: "Bauducco",
    characteristic: "",
    category: "Massas",
    description: "",
    image: "",
  },
  {
    cod: "44",
    name: "Mel",
    price: 30.0,
    unit: "un",
    size: "500g",
    badge: "",
    characteristic: "",
    category: "Doces",
    description: "",
    image: "",
  },
  {
    cod: "45",
    name: "Massa Pastel",
    price: 5.0,
    unit: "un",
    size: "500g",
    badge: "",
    characteristic: "",
    category: "Massas",
    description: "",
    image: "",
  },
  {
    cod: "46",
    name: "Iorgute Danoninho",
    price: 11.0,
    unit: "pacote",
    size: "8 un",
    badge: "",
    characteristic: "",
    category: "Frios",
    description: "",
    image: "",
  },
  {
    cod: "47",
    name: "Bombril",
    price: 2.0,
    unit: "un",
    size: "60g",
    badge: "",
    characteristic: "",
    category: "Limpeza",
    description: "",
    image: "",
  },
  {
    cod: "48",
    name: "Rodo de Pia",
    price: 5.0,
    unit: "un",
    size: "",
    badge: "",
    characteristic: "",
    category: "Limpeza",
    description: "",
    image: "",
  },
];

export default products;
